# Generated by Django 5.2.6 on 2025-10-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="nombre_entidad_principal",
            field=models.CharField(
                default="Alcaldía de",
                help_text="Primera línea del nombre de la entidad (ej. 'Alcaldía de')",
                max_length=100,
                verbose_name="Nombre de la Entidad Principal",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nombre_entidad_secundaria",
            field=models.CharField(
                default="Puerto Gaitán",
                help_text="Segunda línea del nombre de la entidad (ej. 'Puerto Gaitán')",
                max_length=100,
                verbose_name="Nombre de la Entidad Secundaria",
            ),
        ),
    ]
