# Generated by Django 5.2.6 on 2025-10-02 15:55

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_siteconfiguration_nombre_entidad_principal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RutaTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre de la Ruta"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versión del nombre amigable para URLs",
                        max_length=220,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción de la Ruta"),
                ),
                (
                    "imagen_principal",
                    models.ImageField(
                        help_text="Imagen principal que se mostrará en listados y cabeceras.",
                        upload_to=api.models.ruta_turistica_directory_path,
                        verbose_name="Imagen Principal",
                    ),
                ),
                (
                    "es_publicado",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar para que la ruta sea visible en el sitio web público.",
                        verbose_name="Publicado",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "atractivos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rutas",
                        to="api.atractivoturistico",
                        verbose_name="Atractivos en la Ruta",
                    ),
                ),
                (
                    "prestadores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rutas",
                        to="api.prestadorservicio",
                        verbose_name="Prestadores en la Ruta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta Turística",
                "verbose_name_plural": "Rutas Turísticas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenRutaTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=api.models.ruta_turistica_directory_path
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad y SEO",
                        max_length=255,
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="api.rutaturistica",
                    ),
                ),
            ],
        ),
    ]
