# Generated by Django 5.2.6 on 2025-10-02 19:18

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rutaturistica_imagenrutaturistica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="google_api_key",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="openai_api_key",
        ),
        migrations.AddField(
            model_name="customuser",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[("OPENAI", "OpenAI"), ("GOOGLE", "Google")],
                help_text="El proveedor de IA que el usuario prefiere para su asistente personal.",
                max_length=20,
                null=True,
                verbose_name="Proveedor de IA",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="api_key",
            field=api.fields.EncryptedTextField(
                blank=True,
                help_text="La clave de API para el proveedor de IA seleccionado. Se almacena de forma segura.",
                null=True,
                verbose_name="Clave de API Personal",
            ),
        ),
    ]
