# Generated by Django 5.2.6 on 2025-10-02 20:52

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_customuser_google_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artesano",
            name="ubicacion_taller",
        ),
        migrations.RemoveField(
            model_name="atractivoturistico",
            name="ubicacion_mapa",
        ),
        migrations.RemoveField(
            model_name="prestadorservicio",
            name="reporte_ocupacion_internacional",
        ),
        migrations.RemoveField(
            model_name="prestadorservicio",
            name="reporte_ocupacion_nacional",
        ),
        migrations.RemoveField(
            model_name="prestadorservicio",
            name="ubicacion_mapa",
        ),
        migrations.AddField(
            model_name="artesano",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="artesano",
            name="latitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AddField(
            model_name="artesano",
            name="longitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
        migrations.AddField(
            model_name="atractivoturistico",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="atractivoturistico",
            name="latitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AddField(
            model_name="atractivoturistico",
            name="longitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
        migrations.AddField(
            model_name="prestadorservicio",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="prestadorservicio",
            name="foto_principal",
            field=models.ImageField(
                blank=True,
                help_text="Una foto representativa del negocio o servicio.",
                null=True,
                upload_to=api.models.prestador_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="prestadorservicio",
            name="latitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AddField(
            model_name="prestadorservicio",
            name="longitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
        migrations.CreateModel(
            name="DetallesHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporte_ocupacion_nacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
                (
                    "reporte_ocupacion_internacional",
                    models.PositiveIntegerField(
                        default=0, help_text="Exclusivo para hoteles"
                    ),
                ),
                (
                    "prestador",
                    models.OneToOneField(
                        limit_choices_to={"categoria__slug": "hoteles"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_hotel",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalles de Hotel",
                "verbose_name_plural": "Detalles de Hoteles",
            },
        ),
    ]
