# Generated by Django 5.2.6 on 2025-10-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_artesano_ubicacion_taller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="origen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOCAL", "Puerto Gaitán"),
                    ("REGIONAL", "Meta"),
                    ("NACIONAL", "Nacional (Otro Departamento)"),
                    ("EXTRANJERO", "Extranjero"),
                ],
                help_text="Indica la procedencia del turista.",
                max_length=20,
                null=True,
                verbose_name="Origen del Turista",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pais_origen",
            field=models.CharField(
                blank=True,
                help_text="País de origen, si el turista es extranjero.",
                max_length=100,
                null=True,
                verbose_name="País de Origen",
            ),
        ),
    ]
