# Generated by Django 5.2.6 on 2025-10-02 22:27

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_customuser_origen_customuser_pais_origen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenPaginaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=api.models.pagina_institucional_galeria_path,
                        verbose_name="Imagen de Galería",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad y SEO",
                        max_length=255,
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de la imagen en el slider."
                    ),
                ),
                (
                    "pagina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria_imagenes",
                        to="api.paginainstitucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Página Institucional",
                "verbose_name_plural": "Imágenes de Página Institucional",
                "ordering": ["orden"],
            },
        ),
    ]
