# Generated by Django 5.2.6 on 2025-10-07 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_imagenpaginainstitucional"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilAdministrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "dependencia_asignada",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Dependencia Asignada",
                    ),
                ),
                (
                    "nivel_acceso",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nivel de Acceso",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_administrador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Administrador",
                "verbose_name_plural": "Perfiles de Administradores",
            },
        ),
        migrations.CreateModel(
            name="PerfilFuncionarioDirectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependencia",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Dependencia",
                    ),
                ),
                (
                    "nivel_direccion",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nivel de Dirección",
                    ),
                ),
                (
                    "area_funcional",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Área Funcional",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_funcionario_directivo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Funcionario Directivo",
                "verbose_name_plural": "Perfiles de Funcionarios Directivos",
            },
        ),
        migrations.CreateModel(
            name="PerfilFuncionarioProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependencia",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Dependencia",
                    ),
                ),
                (
                    "profesion",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Profesión"
                    ),
                ),
                (
                    "area_asignada",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Área Asignada",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_funcionario_profesional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Funcionario Profesional",
                "verbose_name_plural": "Perfiles de Funcionarios Profesionales",
            },
        ),
    ]
