# Generated by Django 5.2.6 on 2025-09-27 02:37

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_poblar_contenido_secretaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_api_key",
            field=api.fields.EncryptedTextField(
                blank=True, null=True, verbose_name="Google API Key"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="openai_api_key",
            field=api.fields.EncryptedTextField(
                blank=True, null=True, verbose_name="OpenAI API Key"
            ),
        ),
    ]
