# Generated by Django 5.2.6 on 2025-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_perfiladministrador_perfilfuncionariodirectivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ai_provider",
            field=models.CharField(
                blank=True,
                choices=[("OPENAI", "OpenAI"), ("GOOGLE", "Google"), ("GROQ", "Groq")],
                help_text="El proveedor de IA que el usuario prefiere para su asistente personal.",
                max_length=20,
                null=True,
                verbose_name="Proveedor de IA",
            ),
        ),
    ]
