# Generated by Django 5.2.6 on 2025-09-27 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customuser_google_api_key_customuser_openai_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "command",
                    models.TextField(
                        help_text="El comando en lenguaje natural que inició la tarea.",
                        verbose_name="Comando del Usuario",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En Ejecución"),
                            ("COMPLETED", "Completada"),
                            ("FAILED", "Fallida"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado de la Tarea",
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="El informe final generado por el agente al completar la tarea.",
                        null=True,
                        verbose_name="Informe Final",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Agente",
                "verbose_name_plural": "Tareas de Agentes",
                "ordering": ["-created_at"],
            },
        ),
    ]
