# Generated by Django 5.2.6 on 2025-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_customuser_ai_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="llm_routing_token_threshold",
            field=models.PositiveIntegerField(
                default=1500,
                help_text="Número de tokens en el historial de conversación para escalar al LLM avanzado (ej: Groq).",
                verbose_name="Umbral de Tokens para Router LLM",
            ),
        ),
    ]
