# Generated by Django 5.2.6 on 2025-09-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_agenttask"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "horario_atencion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Horario de Atención"
                    ),
                ),
                (
                    "telefono_conmutador",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono Conmutador"
                    ),
                ),
                (
                    "telefono_movil",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono Móvil"
                    ),
                ),
                (
                    "linea_gratuita",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Línea de Atención Gratuita",
                    ),
                ),
                (
                    "linea_anticorrupcion",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Línea Anticorrupción"
                    ),
                ),
                (
                    "correo_institucional",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo Institucional"
                    ),
                ),
                (
                    "correo_notificaciones",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Correo de Notificaciones Judiciales",
                    ),
                ),
                (
                    "social_facebook",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "social_twitter",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "social_youtube",
                    models.URLField(blank=True, verbose_name="YouTube URL"),
                ),
                (
                    "social_instagram",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuración del Sitio",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Enlace"),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Ruta interna (ej: /quienes-somos) o URL completa (ej: https://...).",
                        max_length=255,
                        verbose_name="URL o Ruta",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de aparición (0 primero, 1 después, etc.).",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dejar en blanco si es un elemento del menú principal.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.menuitem",
                        verbose_name="Menú Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento de Menú",
                "verbose_name_plural": "Elementos de Menú",
                "ordering": ["orden"],
            },
        ),
    ]
