# Generated by Django 5.2.6 on 2025-10-10 10:55

import api.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_siteconfiguration_llm_routing_token_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="ai_provider",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="api_key",
        ),
        migrations.CreateModel(
            name="UserLLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("SYSTEM_DEFAULT", "Usar Configuración del Sistema"),
                            ("GROQ", "Groq Personalizado"),
                            ("PHI3_LOCAL", "Modelo Local Phi-3 Mini"),
                            ("PHI4_LOCAL", "Modelo Local Phi-4"),
                        ],
                        default="SYSTEM_DEFAULT",
                        help_text="El proveedor de LLM que el usuario prefiere usar.",
                        max_length=50,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "api_key",
                    api.fields.EncryptedTextField(
                        blank=True,
                        help_text="La clave de API para el proveedor seleccionado (ej. Groq). Se almacena de forma segura.",
                        null=True,
                        verbose_name="Clave de API Personalizada",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración LLM de Usuario",
                "verbose_name_plural": "Configuraciones LLM de Usuarios",
            },
        ),
    ]
