# Generated by Django 5.2.6 on 2025-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_userllmconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userllmconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("SYSTEM_DEFAULT", "Usar configuración del sistema"),
                    ("GROQ", "Groq personalizado"),
                    ("PHI3_LOCAL", "Modelo local Phi-3 Mini"),
                    ("PHI4_LOCAL", "Modelo local Phi-4"),
                ],
                default="SYSTEM_DEFAULT",
                help_text="El proveedor de LLM que el usuario prefiere usar.",
                max_length=50,
                verbose_name="Proveedor LLM",
            ),
        ),
    ]
