# Generated by Django 5.2.6 on 2025-09-27 20:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_siteconfiguration_menuitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("BANNER", "Banner Principal"),
                            ("SLIDER", "Slider Secundario"),
                            ("CARD", "Tarjeta de Información"),
                        ],
                        default="BANNER",
                        max_length=20,
                        verbose_name="Tipo de Componente",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagen principal para el componente.",
                        upload_to=api.models.homepage_component_directory_path,
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="El enlace al que dirigirá el componente al hacer clic.",
                        null=True,
                        verbose_name="URL de Destino",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Orden de visualización (0 primero, 1 después...).",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Marcar para que el componente sea visible en la página de inicio.",
                        verbose_name="Activo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Componente de Página de Inicio",
                "verbose_name_plural": "Componentes de Página de Inicio",
                "ordering": ["order"],
            },
        ),
    ]
