# Generated by Django 5.2.6 on 2025-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_homepagecomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="seccion_atractivos_activa",
            field=models.BooleanField(
                default=True,
                help_text="Marcar para mostrar la sección de atractivos turísticos.",
                verbose_name="Sección de Atractivos Turísticos Activa",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="seccion_prestadores_activa",
            field=models.BooleanField(
                default=True,
                help_text="Marcar para mostrar el directorio de prestadores de servicios.",
                verbose_name="Sección de Prestadores de Servicios Activa",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="seccion_publicaciones_activa",
            field=models.BooleanField(
                default=True,
                help_text="Marcar para mostrar la sección de publicaciones en el sitio web.",
                verbose_name="Sección de Publicaciones (Eventos/Noticias) Activa",
            ),
        ),
    ]
