# Generated by Django 5.2.6 on 2025-09-27 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_siteconfiguration_seccion_atractivos_activa_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_CREATE", "Usuario Creado"),
                            ("USER_UPDATE", "Usuario Actualizado"),
                            ("USER_DELETE", "Usuario Eliminado"),
                            ("MENU_CREATE", "Elemento de Menú Creado"),
                            ("MENU_UPDATE", "Elemento de Menú Actualizado"),
                            ("MENU_DELETE", "Elemento de Menú Eliminado"),
                            (
                                "SITE_CONFIG_UPDATE",
                                "Configuración del Sitio Actualizada",
                            ),
                            ("COMPONENT_CREATE", "Componente de Inicio Creado"),
                            ("COMPONENT_UPDATE", "Componente de Inicio Actualizado"),
                            ("COMPONENT_DELETE", "Componente de Inicio Eliminado"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la acción o los datos cambiados (ej. en formato JSON).",
                        null=True,
                        verbose_name="Detalles",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría",
                "verbose_name_plural": "Registros de Auditoría",
                "ordering": ["-timestamp"],
            },
        ),
    ]
