# Generated by Django 5.2.6 on 2025-09-27 20:10

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_maps_api_key",
            field=api.fields.EncryptedTextField(
                blank=True,
                help_text="Clave de API de Google Maps para todo el sitio.",
                null=True,
                verbose_name="Google Maps API Key",
            ),
        ),
    ]
