# Generated by Django 5.2.6 on 2025-09-28 01:06

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_CREATE", "Usuario Creado"),
                    ("USER_UPDATE", "Usuario Actualizado"),
                    ("USER_DELETE", "Usuario Eliminado"),
                    ("MENU_CREATE", "Elemento de Menú Creado"),
                    ("MENU_UPDATE", "Elemento de Menú Actualizado"),
                    ("MENU_DELETE", "Elemento de Menú Eliminado"),
                    ("SITE_CONFIG_UPDATE", "Configuración del Sitio Actualizada"),
                    ("COMPONENT_CREATE", "Componente de Inicio Creado"),
                    ("COMPONENT_UPDATE", "Componente de Inicio Actualizado"),
                    ("COMPONENT_DELETE", "Componente de Inicio Eliminado"),
                    ("COMPONENT_REORDER", "Componentes de Inicio Reordenados"),
                    ("CONTENIDO_CREATE", "Contenido de Municipio Creado"),
                    ("CONTENIDO_UPDATE", "Contenido de Municipio Actualizado"),
                    ("CONTENIDO_DELETE", "Contenido de Municipio Eliminado"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.CreateModel(
            name="PaginaInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre de la Página"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para la URL. Ej: secretaria-turismo",
                        max_length=150,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "titulo_banner",
                    models.CharField(
                        help_text="Título principal que se superpone en el banner.",
                        max_length=200,
                        verbose_name="Título del Banner",
                    ),
                ),
                (
                    "subtitulo_banner",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Subtítulo del Banner",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        help_text="Imagen principal que se mostrará en la parte superior de la página.",
                        upload_to=api.models.pagina_institucional_banner_path,
                        verbose_name="Imagen de Banner",
                    ),
                ),
                (
                    "contenido_principal",
                    models.TextField(
                        blank=True,
                        help_text="Sección de objetivos y funciones. Acepta formato Markdown.",
                        verbose_name="Contenido Principal",
                    ),
                ),
                (
                    "programas_proyectos",
                    models.TextField(
                        blank=True,
                        help_text="Sección para listar programas y proyectos en curso. Acepta formato Markdown.",
                        verbose_name="Programas y Proyectos",
                    ),
                ),
                (
                    "estrategias_apoyo",
                    models.TextField(
                        blank=True,
                        help_text="Sección para detallar el apoyo a empresarios. Acepta formato Markdown.",
                        verbose_name="Estrategias de Apoyo",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["ADMIN", "FUNCIONARIO"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Página Institucional",
                "verbose_name_plural": "Páginas Institucionales",
                "ordering": ["nombre"],
            },
        ),
    ]
