# Generated by Django 5.2.6 on 2025-09-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_CREATE", "Usuario Creado"),
                    ("USER_UPDATE", "Usuario Actualizado"),
                    ("USER_DELETE", "Usuario Eliminado"),
                    ("MENU_CREATE", "Elemento de Menú Creado"),
                    ("MENU_UPDATE", "Elemento de Menú Actualizado"),
                    ("MENU_DELETE", "Elemento de Menú Eliminado"),
                    ("SITE_CONFIG_UPDATE", "Configuración del Sitio Actualizada"),
                    ("COMPONENT_CREATE", "Componente de Inicio Creado"),
                    ("COMPONENT_UPDATE", "Componente de Inicio Actualizado"),
                    ("COMPONENT_DELETE", "Componente de Inicio Eliminado"),
                    ("COMPONENT_REORDER", "Componentes de Inicio Reordenados"),
                    ("CONTENIDO_CREATE", "Contenido de Municipio Creado"),
                    ("CONTENIDO_UPDATE", "Contenido de Municipio Actualizado"),
                    ("CONTENIDO_DELETE", "Contenido de Municipio Eliminado"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador General"),
                    ("FUNCIONARIO", "Funcionario de Turismo"),
                    ("PRESTADOR", "Prestador de Servicio"),
                    ("ARTESANO", "Artesano"),
                    ("TURISTA", "Turista"),
                ],
                max_length=50,
                verbose_name="Rol",
            ),
        ),
    ]
