# Generated by Django 5.2.6 on 2025-09-27 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_auditlog_action_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atractivoturistico",
            name="autor",
            field=models.ForeignKey(
                help_text="Funcionario o Administrador que creó el registro.",
                limit_choices_to={
                    "role__in": [
                        "ADMIN",
                        "FUNCIONARIO_DIRECTIVO",
                        "FUNCIONARIO_PROFESIONAL",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contenidomunicipio",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuario que modificó este contenido.",
                limit_choices_to={
                    "role__in": [
                        "ADMIN",
                        "FUNCIONARIO_DIRECTIVO",
                        "FUNCIONARIO_PROFESIONAL",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador General"),
                    ("FUNCIONARIO_DIRECTIVO", "Funcionario Directivo"),
                    ("FUNCIONARIO_PROFESIONAL", "Funcionario Profesional"),
                    ("PRESTADOR", "Prestador de Servicio"),
                    ("ARTESANO", "Artesano"),
                    ("TURISTA", "Turista"),
                ],
                max_length=50,
                verbose_name="Rol",
            ),
        ),
    ]
