# Generated by Django 5.2.6 on 2025-09-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_auditlog_action_paginainstitucional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenidomunicipio",
            name="seccion",
            field=models.CharField(
                choices=[
                    ("INTRODUCCION", "Introducción General"),
                    ("UBICACION_CLIMA", "Ubicación y Clima"),
                    ("ALOJAMIENTO", "Alojamiento y Hotelería"),
                    ("COMO_LLEGAR", "¿Cómo Llegar?"),
                    ("CONTACTOS", "Contactos de Interés"),
                    ("FINANZAS", "Entidades Financieras"),
                    (
                        "SECRETARIA_TURISMO",
                        "Secretaría de Turismo y Desarrollo Económico",
                    ),
                    (
                        "DIRECTORIO_FUNCIONARIOS",
                        "Directorio - Funcionarios y Dependencias",
                    ),
                    ("DIRECTORIO_ENLACES", "Directorio - Enlaces de Interés"),
                    ("OTRA", "Otra Sección"),
                ],
                help_text="Agrupa el contenido bajo una categoría temática.",
                max_length=50,
                verbose_name="Sección Temática",
            ),
        ),
    ]
