# Generated by Django 5.2.6 on 2025-09-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_atractivoturistico_autor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consejoconsultivo",
            name="es_publicado",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para que el contenido sea visible en el sitio web público.",
            ),
        ),
        migrations.AddField(
            model_name="contenidomunicipio",
            name="es_publicado",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para que el contenido sea visible en el sitio web público.",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="es_publicado",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para que el video sea visible en el sitio web público.",
            ),
        ),
        migrations.AlterField(
            model_name="publicacion",
            name="es_publicado",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para que el contenido sea visible en el sitio web público.",
            ),
        ),
    ]
