# Generated by Django 5.2.6 on 2025-09-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_contenidomunicipio_seccion"),
        ("api", "0019_consejoconsultivo_es_publicado_and_more"),
    ]

    operations = []
