# Generated by Django 5.2.6 on 2025-09-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_merge_20250928_0935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paginainstitucional",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__in": [
                        "ADMIN",
                        "FUNCIONARIO_DIRECTIVO",
                        "FUNCIONARIO_PROFESIONAL",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
