# Generated by Django 5.2.6 on 2025-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_paginainstitucional_actualizado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="paginainstitucional",
            name="convenios_asociaciones",
            field=models.TextField(
                blank=True,
                help_text="Para la Dirección. Acepta formato Markdown.",
                verbose_name="Convenios y Asociaciones",
            ),
        ),
        migrations.AddField(
            model_name="paginainstitucional",
            name="informes_resultados",
            field=models.TextField(
                blank=True,
                help_text="Para la Dirección. Acepta formato Markdown.",
                verbose_name="Informes de Resultados",
            ),
        ),
        migrations.AddField(
            model_name="paginainstitucional",
            name="politicas_locales",
            field=models.TextField(
                blank=True,
                help_text="Para la Dirección. Acepta formato Markdown.",
                verbose_name="Políticas Locales de Turismo",
            ),
        ),
        migrations.AlterField(
            model_name="paginainstitucional",
            name="contenido_principal",
            field=models.TextField(
                blank=True,
                help_text="Acepta formato Markdown.",
                verbose_name="Contenido Principal (Objetivos y Funciones)",
            ),
        ),
        migrations.AlterField(
            model_name="paginainstitucional",
            name="estrategias_apoyo",
            field=models.TextField(
                blank=True,
                help_text="Para la Secretaría. Acepta formato Markdown.",
                verbose_name="Estrategias de Apoyo",
            ),
        ),
        migrations.AlterField(
            model_name="paginainstitucional",
            name="programas_proyectos",
            field=models.TextField(
                blank=True,
                help_text="Para la Secretaría. Acepta formato Markdown.",
                verbose_name="Programas y Proyectos",
            ),
        ),
    ]
