# Generated by Django 5.2.6 on 2025-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_add_fields_to_pagina_institucional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacion",
            name="subcategoria_evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CULTURAL", "Cultural"),
                    ("DEPORTIVO", "Deportivo"),
                    ("RELIGIOSO", "Religioso"),
                    ("CIVICO", "Cívico"),
                    ("OTRO", "Otro"),
                ],
                help_text="Clasificación específica solo para eventos.",
                max_length=50,
                null=True,
                verbose_name="Subcategoría de Evento",
            ),
        ),
    ]
