# Generated by Django 5.2.6 on 2025-09-28 16:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_event_subcategories"),
    ]

    operations = [
        migrations.CreateModel(
            name="HechoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="Año del Acontecimiento")),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título del Hecho"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen opcional para ilustrar el hecho histórico.",
                        null=True,
                        upload_to=api.models.hecho_historico_directory_path,
                        verbose_name="Imagen Ilustrativa",
                    ),
                ),
                (
                    "es_publicado",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar para que sea visible en la línea de tiempo pública.",
                        verbose_name="Publicado",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hecho Histórico",
                "verbose_name_plural": "Hechos Históricos",
                "ordering": ["ano"],
            },
        ),
    ]
