# Generated by Django 5.2.6 on 2025-09-28 17:40

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_hecho_historico_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="RubroArtesano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versión del nombre amigable para URLs",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro de Artesano",
                "verbose_name_plural": "Rubros de Artesanos",
            },
        ),
        migrations.CreateModel(
            name="Artesano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_taller",
                    models.CharField(
                        help_text="Nombre del taller o marca personal del artesano.",
                        max_length=200,
                    ),
                ),
                (
                    "nombre_artesano",
                    models.CharField(
                        help_text="Nombre completo del artesano.", max_length=200
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "email_contacto",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "foto_principal",
                    models.ImageField(
                        blank=True,
                        help_text="Una foto representativa del artesano o sus productos.",
                        null=True,
                        upload_to=api.models.artesano_directory_path,
                    ),
                ),
                ("red_social_facebook", models.URLField(blank=True, null=True)),
                ("red_social_instagram", models.URLField(blank=True, null=True)),
                (
                    "red_social_whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Número de WhatsApp con código de país",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ubicacion_taller",
                    models.CharField(
                        blank=True,
                        help_text="Dirección o punto de referencia del taller o punto de venta.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        default=False,
                        help_text="El administrador debe aprobar este perfil para que sea visible.",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_artesano",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artesanos",
                        to="api.rubroartesano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artesano",
                "verbose_name_plural": "Artesanos",
            },
        ),
    ]
