# Generated by Django 5.2.6 on 2025-09-28 19:05

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rubroartesano_artesano"),
    ]

    operations = [
        migrations.AddField(
            model_name="artesano",
            name="red_social_tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestadorservicio",
            name="red_social_tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ImagenArtesano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to=api.models.galeria_artesano_directory_path
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad",
                        max_length=255,
                    ),
                ),
                (
                    "artesano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria_imagenes",
                        to="api.artesano",
                    ),
                ),
            ],
        ),
    ]
