# Generated by Django 5.2.6 on 2025-09-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_resena"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sugerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="Nombre de quien envía el mensaje.", max_length=150
                    ),
                ),
                (
                    "email_contacto",
                    models.EmailField(
                        help_text="Correo electrónico de contacto.", max_length=254
                    ),
                ),
                (
                    "tipo_mensaje",
                    models.CharField(
                        choices=[
                            ("SUGERENCIA", "Sugerencia"),
                            ("QUEJA", "Queja"),
                            ("FELICITACION", "Felicitación"),
                        ],
                        default="SUGERENCIA",
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDO", "Recibido"),
                            ("EN_REVISION", "En Revisión"),
                            ("ATENDIDO", "Atendido"),
                        ],
                        default="RECIBIDO",
                        max_length=20,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "es_publico",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si esta sugerencia/felicitación puede ser mostrada públicamente.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sugerencia o Felicitación",
                "verbose_name_plural": "Sugerencias y Felicitaciones",
                "ordering": ["-fecha_envio"],
            },
        ),
    ]
