# Generated by Django 5.2.6 on 2025-09-28 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_sugerencia"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sugerencia",
            name="email_contacto",
        ),
        migrations.RemoveField(
            model_name="sugerencia",
            name="nombre_completo",
        ),
        migrations.AddField(
            model_name="sugerencia",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="sugerencia",
            name="email_remitente",
            field=models.EmailField(
                blank=True,
                help_text="Email de contacto (si el usuario no está autenticado).",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sugerencia",
            name="nombre_remitente",
            field=models.CharField(
                blank=True,
                help_text="Nombre (si el usuario no está autenticado).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="sugerencia",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sugerencia",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sugerencias_hechas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
