# Generated by Django 5.2.6 on 2025-09-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_caracterizacionempresaeventos"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracterizacionAgroturismo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(blank=True, max_length=255)),
                ("camara_comercio_nit", models.CharField(blank=True, max_length=50)),
                ("rnt_numero", models.CharField(blank=True, max_length=50)),
                ("ruta_turistica", models.CharField(blank=True, max_length=100)),
                ("pagina_web", models.URLField(blank=True, null=True)),
                (
                    "email_contacto",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("telefono_fax", models.CharField(blank=True, max_length=50)),
                ("tiene_normas_sectoriales", models.BooleanField(default=False)),
                (
                    "certificacion_recibida",
                    models.CharField(blank=True, max_length=255),
                ),
                ("sello_ambiental_colombiano", models.BooleanField(default=False)),
                ("otras_certificaciones", models.TextField(blank=True)),
                ("pertenece_gremio_turismo", models.BooleanField(default=False)),
                ("nombre_gremio", models.CharField(blank=True, max_length=255)),
                (
                    "servicios_ofrecidos",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'hospedaje': true, 'restaurante': false}",
                    ),
                ),
                (
                    "caracteristicas_agroturismo",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'agricola': true, 'pecuaria': false}",
                    ),
                ),
                (
                    "especialidad_agricola",
                    models.JSONField(
                        default=dict, help_text="Ej: {'arroz': true, 'cacao': false}"
                    ),
                ),
                (
                    "especialidad_pecuaria",
                    models.JSONField(
                        default=dict, help_text="Ej: {'bovino': true, 'equinos': false}"
                    ),
                ),
                (
                    "especialidad_avicola",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'gallinas_campo': true, 'patos': false}",
                    ),
                ),
                (
                    "especialidad_agroindustrial",
                    models.JSONField(
                        default=dict, help_text="Ej: {'lacteos': true, 'vinos': false}"
                    ),
                ),
                (
                    "actividades_agricolas",
                    models.JSONField(
                        default=dict, help_text="Detalle de actividades agrícolas"
                    ),
                ),
                (
                    "actividades_avicolas",
                    models.JSONField(
                        default=dict, help_text="Detalle de actividades avícolas"
                    ),
                ),
                (
                    "actividades_agroindustriales",
                    models.JSONField(
                        default=dict,
                        help_text="Detalle de actividades agroindustriales",
                    ),
                ),
                (
                    "actividades_pecuarias",
                    models.JSONField(
                        default=dict, help_text="Detalle de actividades pecuarias"
                    ),
                ),
                (
                    "actividades_piscicultura",
                    models.JSONField(
                        default=dict, help_text="Detalle de actividades de piscicultura"
                    ),
                ),
                (
                    "actividades_ecoturismo",
                    models.JSONField(
                        default=dict, help_text="Detalle de actividades de ecoturismo"
                    ),
                ),
                (
                    "actividades_turismo_aventura",
                    models.JSONField(
                        default=dict,
                        help_text="Detalle de actividades de turismo de aventura",
                    ),
                ),
                (
                    "otras_actividades_turismo",
                    models.JSONField(
                        default=dict, help_text="Otras actividades de turismo"
                    ),
                ),
                (
                    "caracteristicas_a_potencializar",
                    models.JSONField(
                        default=dict, help_text="Características a potencializar"
                    ),
                ),
                ("otras_actividades_a_potencializar", models.TextField(blank=True)),
                (
                    "formacion_asesoria_deseada",
                    models.JSONField(
                        default=dict, help_text="Temas de formación y asesoría deseados"
                    ),
                ),
                ("protocolos_seguridad", models.BooleanField(default=False)),
                ("protocolos_bioseguridad", models.BooleanField(default=False)),
                ("cumple_lineamientos_escnna", models.BooleanField(default=False)),
                ("tiene_polizas", models.BooleanField(default=False)),
                ("nombre_polizas", models.CharField(blank=True, max_length=255)),
                ("espacios_salvaguarda_cultura", models.BooleanField(default=False)),
                ("realiza_actividades_culturales", models.BooleanField(default=False)),
                ("descripcion_actividades_culturales", models.TextField(blank=True)),
                ("realiza_actividades_llaneridad", models.BooleanField(default=False)),
                ("descripcion_actividades_llaneridad", models.TextField(blank=True)),
                (
                    "medios_promocion",
                    models.JSONField(
                        default=dict, help_text="Medios de promoción utilizados"
                    ),
                ),
                (
                    "datos_encuestado",
                    models.JSONField(
                        default=dict,
                        help_text="Datos de la persona que diligencia el formulario",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracterizacion_agroturismo",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caracterización de Agroturismo",
                "verbose_name_plural": "Caracterizaciones de Agroturismo",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
    ]
