# Generated by Django 5.2.6 on 2025-09-29 17:01

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_caracterizacionagroturismo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracterizacionGuiaTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres_apellidos", models.CharField(blank=True, max_length=255)),
                ("documento_identidad", models.CharField(blank=True, max_length=50)),
                ("direccion_ubicacion", models.CharField(blank=True, max_length=255)),
                ("municipio", models.CharField(blank=True, max_length=100)),
                ("vereda_localidad", models.CharField(blank=True, max_length=100)),
                ("telefono_fijo", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("pagina_web", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.guia_turistico_foto_path,
                    ),
                ),
                (
                    "tipo_guia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROFESIONAL", "Guía de Turismo Profesional"),
                            ("ACOMPANANTE", "Guía de Turismo Acompañante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tiene_rnt", models.BooleanField(default=False)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("MASCULINO", "Masculino"), ("FEMENINO", "Femenino")],
                        max_length=10,
                    ),
                ),
                ("pertenece_lgtbi", models.BooleanField(default=False)),
                (
                    "discapacidad",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de discapacidad, si aplica",
                        max_length=255,
                    ),
                ),
                (
                    "grupo_atencion_especial",
                    models.CharField(
                        blank=True,
                        help_text="Grupo de atención especial, si aplica",
                        max_length=255,
                    ),
                ),
                (
                    "especialidades",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'agroturismo': true, 'aviturismo': false}",
                    ),
                ),
                (
                    "forma_prestacion_servicio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECTA", "Directa (sin intermediarios)"),
                            ("EMPRESA", "Trabajo directamente para una empresa"),
                            ("INDIRECTA", "Indirecta (a través de agencia)"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forma_prestacion_servicio_otro",
                    models.CharField(blank=True, max_length=255),
                ),
                ("pertenece_gremio", models.BooleanField(default=False)),
                ("nombre_gremio", models.CharField(blank=True, max_length=255)),
                ("presta_servicios_empresa", models.BooleanField(default=False)),
                (
                    "nombre_empresa_servicio",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "rutas_servicio",
                    models.TextField(
                        blank=True, help_text="Rutas y municipios donde opera"
                    ),
                ),
                (
                    "atractivos_por_municipio",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'Puerto Gaitán': ['Atractivo 1', 'Atractivo 2']}",
                    ),
                ),
                ("tecnologia_guianza_sena", models.BooleanField(default=False)),
                (
                    "numero_tarjeta_profesional",
                    models.CharField(blank=True, max_length=100),
                ),
                ("fecha_tarjeta", models.DateField(blank=True, null=True)),
                ("tiene_rnt_guia", models.BooleanField(default=False)),
                ("numero_rnt_guia", models.CharField(blank=True, max_length=100)),
                (
                    "fecha_actualizacion_rnt_guia",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "experiencia_independiente_anos",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "experiencia_independiente_meses",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "experiencia_sector_privado_anos",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "experiencia_sector_privado_meses",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "idiomas",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'ingles': {'habla': 'B', 'lee': 'MB'}}",
                    ),
                ),
                (
                    "capacitaciones_recibidas",
                    models.JSONField(default=list, help_text="Lista de capacitaciones"),
                ),
                ("realiza_evaluacion_servicio", models.BooleanField(default=False)),
                ("cual_evaluacion", models.CharField(blank=True, max_length=255)),
                (
                    "temas_profundizar",
                    models.TextField(
                        blank=True, help_text="Temas en los que le gustaría profundizar"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "prestador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracterizacion_guia",
                        to="api.prestadorservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caracterización de Guía Turístico",
                "verbose_name_plural": "Caracterizaciones de Guías Turísticos",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
    ]
