# Generated by Django 5.2.6 on 2025-09-29 17:06

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_caracterizacionguiaturistico"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracterizacionArtesano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento_identidad", models.CharField(blank=True, max_length=50)),
                ("direccion_ubicacion", models.CharField(blank=True, max_length=255)),
                ("municipio", models.CharField(blank=True, max_length=100)),
                ("vereda_localidad", models.CharField(blank=True, max_length=100)),
                ("telefono_fijo", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("pagina_web", models.URLField(blank=True)),
                ("tiene_registro_artesano", models.BooleanField(default=False)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to=api.models.artesano_foto_path
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("MASCULINO", "Masculino"), ("FEMENINO", "Femenino")],
                        max_length=10,
                    ),
                ),
                ("pertenece_lgtbi", models.BooleanField(default=False)),
                (
                    "discapacidad",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de discapacidad, si aplica",
                        max_length=255,
                    ),
                ),
                (
                    "grupo_atencion_especial",
                    models.CharField(
                        blank=True,
                        help_text="Grupo de atención especial, si aplica",
                        max_length=255,
                    ),
                ),
                (
                    "tipo_artesania",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INDIGENA", "Artesanía Indígena"),
                            ("CONTEMPORANEA", "Artesanía Contemporánea o Neoartesanía"),
                            ("TRADICIONAL", "Tradicional popular"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo_artesania_otra", models.CharField(blank=True, max_length=255)),
                (
                    "origen_produccion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUBSISTENCIA", "Economía de subsistencia"),
                            ("NUCLEO", "Núcleo Artesanales"),
                            ("URBANA", "Producción Urbana"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "origen_produccion_otro",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "oficios_artesanales",
                    models.JSONField(
                        default=dict, help_text="Ej: {'madera': true, 'vidrio': false}"
                    ),
                ),
                ("producto_principal", models.CharField(blank=True, max_length=255)),
                (
                    "materia_prima_principal",
                    models.CharField(blank=True, max_length=255),
                ),
                ("tecnica_utilizada", models.CharField(blank=True, max_length=255)),
                ("descripcion_proceso", models.TextField(blank=True)),
                ("pertenece_gremio", models.BooleanField(default=False)),
                ("nombre_gremio", models.CharField(blank=True, max_length=255)),
                (
                    "forma_comercializacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "DIRECTA",
                                "Directa (Vendo mis productos al cliente final)",
                            ),
                            ("EMPRESA", "Trabajo directamente para una empresa"),
                            (
                                "INDIRECTA",
                                "Indirecta (Vendo a empresas para ser comercializados)",
                            ),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forma_comercializacion_otra",
                    models.CharField(blank=True, max_length=255),
                ),
                ("ofrece_productos_empresa", models.BooleanField(default=False)),
                (
                    "nombre_empresa_comercializa",
                    models.CharField(blank=True, max_length=255),
                ),
                ("certificado_aptitud_sena", models.BooleanField(default=False)),
                (
                    "nombre_certificado_sena",
                    models.CharField(blank=True, max_length=255),
                ),
                ("numero_tarjeta_sena", models.CharField(blank=True, max_length=100)),
                ("fecha_tarjeta_sena", models.DateField(blank=True, null=True)),
                (
                    "tiene_registro_nacional_artesano",
                    models.BooleanField(default=False),
                ),
                (
                    "numero_registro_nacional",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "fecha_actualizacion_registro",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "idiomas",
                    models.JSONField(
                        default=dict,
                        help_text="Ej: {'ingles': {'habla': 'B', 'lee': 'MB'}}",
                    ),
                ),
                (
                    "capacitaciones_recibidas",
                    models.JSONField(default=list, help_text="Lista de capacitaciones"),
                ),
                ("temas_profundizar", models.TextField(blank=True)),
                ("elementos_maquinaria_necesaria", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "artesano",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracterizacion",
                        to="api.artesano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caracterización de Artesano",
                "verbose_name_plural": "Caracterizaciones de Artesanos",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
    ]
