# Generated by Django 5.2.6 on 2025-09-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_caracterizacionartesano"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsejoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("municipio", models.CharField(max_length=255)),
                (
                    "acto_administrativo",
                    models.CharField(
                        blank=True,
                        help_text="Acto Administrativo de constitución del Consejo Local",
                        max_length=255,
                    ),
                ),
                (
                    "frecuencia_reunion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MENSUAL", "Mensual"),
                            ("BIMESTRAL", "Bimestral"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frecuencia_reunion_otro",
                    models.CharField(blank=True, max_length=100),
                ),
                ("tiene_matriz_compromisos", models.BooleanField(default=False)),
                (
                    "tiene_plan_accion",
                    models.BooleanField(
                        default=False,
                        help_text="Si es sí, se debería poder adjuntar el plan.",
                    ),
                ),
                (
                    "plan_accion_adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="consejos_locales/planes/"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consejo Local de Turismo",
                "verbose_name_plural": "Consejos Locales de Turismo",
                "ordering": ["municipio"],
            },
        ),
        migrations.CreateModel(
            name="IntegranteConsejo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("sector_representa", models.CharField(blank=True, max_length=255)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEMENINO", "Femenino"),
                            ("MASCULINO", "Masculino"),
                            ("LGTBI", "LGTBI"),
                            ("NA", "No Aplica"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grupo_atencion_especial",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Desplazado, Afrodescendiente, Indígena, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "tipo_discapacidad",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Motora, Auditiva, Visual, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "consejo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrantes",
                        to="api.consejolocal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrante de Consejo Local",
                "verbose_name_plural": "Integrantes de Consejos Locales",
                "ordering": ["nombre_completo"],
            },
        ),
    ]
