# Generated by Django 5.2.6 on 2025-09-29 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_consejolocal_integranteconsejo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticoRutaTuristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_ruta", models.CharField(max_length=255, unique=True)),
                ("descripcion_general", models.TextField(blank=True)),
                (
                    "actores_cadena_valor",
                    models.JSONField(
                        default=list,
                        help_text="Lista de actores por municipio. Ej: [{'municipio': '...', 'actores': [{'tipo': 'Alojamiento', 'nombre': '...', 'caracterizado': true}]}]",
                    ),
                ),
                (
                    "entidades_responsables",
                    models.JSONField(
                        default=list,
                        help_text="Lista de entidades y sus responsables. Ej: [{'entidad': '...', 'responsable': '...', 'contacto': '...'}]",
                    ),
                ),
                (
                    "eventos_turisticos",
                    models.JSONField(
                        default=list,
                        help_text="Lista de eventos/festividades. Ej: [{'evento': '...', 'municipio': '...', 'fecha': '...'}]",
                    ),
                ),
                (
                    "atractivos_turisticos",
                    models.JSONField(
                        default=list,
                        help_text="Lista de atractivos. Ej: [{'nombre': '...', 'descripcion': '...', 'tipo': '...'}]",
                    ),
                ),
                ("vias_acceso", models.TextField(blank=True)),
                ("transporte", models.TextField(blank=True)),
                ("senalizacion", models.TextField(blank=True)),
                ("energia", models.TextField(blank=True)),
                ("comunicaciones", models.TextField(blank=True)),
                (
                    "distancia_desde_villavicencio",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "actividades_situr",
                    models.TextField(blank=True, verbose_name="Actividades SITUR"),
                ),
                (
                    "actividades_escnna",
                    models.TextField(blank=True, verbose_name="Actividades ESCNNA"),
                ),
                (
                    "actividades_rnt",
                    models.TextField(blank=True, verbose_name="Actividades RNT"),
                ),
                (
                    "actividades_formacion",
                    models.TextField(
                        blank=True, verbose_name="Actividades Formación y Capacitación"
                    ),
                ),
                (
                    "actividades_promocion",
                    models.TextField(
                        blank=True, verbose_name="Actividades Promoción y Difusión"
                    ),
                ),
                (
                    "actividades_nts",
                    models.TextField(blank=True, verbose_name="Actividades NTS"),
                ),
                (
                    "actividades_asociatividad",
                    models.TextField(
                        blank=True, verbose_name="Actividades Asociatividad"
                    ),
                ),
                (
                    "actividades_cat",
                    models.TextField(
                        blank=True,
                        verbose_name="Actividades Colegios Amigos del Turismo",
                    ),
                ),
                ("fecha_elaboracion", models.DateField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "elaborado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosticos_elaborados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico de Ruta Turística",
                "verbose_name_plural": "Diagnósticos de Rutas Turísticas",
                "ordering": ["nombre_ruta"],
            },
        ),
    ]
