version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: turismo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app/frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend

volumes:
  postgres_data: