version: '3.9'
services:
  backend:
    build: .
    container_name: backend_test
    command: python backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    image: node:20
    working_dir: /app/frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: turismo
    ports:
      - "5432:5432"