name: Verificación Controlada del Sistema

on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: turismo_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 1. Checkout del Repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 3. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: 4. Instalar Dependencias del Backend
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: 5. Instalar Dependencias del Frontend
        run: npm install --prefix frontend

      - name: 6. Instalar Navegadores de Playwright
        run: npx playwright install --with-deps --prefix frontend

      - name: 7. Ejecutar Migraciones del Backend
        env:
          DATABASE_URL: postgres://admin:admin@localhost:5432/turismo_test
          DJANGO_SETTINGS_MODULE: puerto_gaitan_turismo.settings
        run: python backend/manage.py migrate

      - name: 8. Iniciar Servidor del Backend en Segundo Plano
        env:
          DATABASE_URL: postgres://admin:admin@localhost:5432/turismo_test
          DJANGO_SETTINGS_MODULE: puerto_gaitan_turismo.settings
        run: python backend/manage.py runserver &

      - name: 9. Iniciar Servidor del Frontend en Segundo Plano
        run: npm run dev --prefix frontend &

      - name: Esperar a que los servidores arranquen
        run: sleep 30

      - name: 10. Ejecutar Pruebas de Playwright
        run: npx playwright test --config frontend/playwright.config.ts

      - name: 11. Subir Artefactos de Pruebas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7